chore: set permissions for routes
d-x-s/airon-fitness pull request #35
Opened 2023-06-25 20:36 UTC by d-x-s

### **CUSTOM INPUTS**
PRIVATE: router.get('/:userID', getCustomInputsByUser);
- Retrieve personalized data for a particular user

PRIVATE: router.post('/', addCustomInput);
- Users need be authenticated to submit inputs

### **MEAL SCHEDULES**
PRIVATE: router.get('/:userID', getMealScheduleByUser);
- Retrieve personalized data for a particular user

PRIVATE: router.post('/', createMealScheduleForUser);
- Users need to be authenticated to create a meal schedule

PRIVATE: router.put('/:userID', updateMealScheduleForUser);
- Users need to be authenticated to update their meal schedule

### **USER PROFILES**
(?) Can expose certain fields in a UserProfile if we want to enable profiles to connect with each other
PRIVATE: router.get('/', getAllUserProfiles);
- Profiles are confidential information

PRIVATE: router.get('/:userID', getUserProfileById);
- A single profile is confidential

PRIVATE: router.post('/', createUserProfile);
- a user must be authenticated to add finish generating their profile

PRIVATE: router.put('/:userID', updateUserProfile);
- a user must be authenticated to update their own profile

PRIVATE: router.delete('/:userID', deleteUserProfileById);
- a user must be authenticated to delete their own profile

### **WORKOUT SCHEDULES**
(?) Change to public if we want to enable schedule sharing between users (I.E. lookup your friends profile and download their schedule)
PRIVATE: router.get('/:userID', getWorkoutScheduleByUserID);
- a user may only view their own schedule when logged in

PRIVATE: router.post('/', createWorkoutSchedule);
- a user must be authenticated to create their own schedule

PRIVATE: router.put('/:userID', updateUserWorkoutScheduleByUserID);
- a user must be authenticated to update their own schedule

2023-06-25 20:44 UTC, ckev07 submitted a review, later dismissed

2023-06-25 21:00 UTC, kennyjhcheng commented
@d-x-s for any private routes (all of the routes in this PR basically), add the middleware, and ensure that the controllers are also documented similarly.

2023-06-26 21:34 UTC, jakji93 submitted a review, later dismissed

2023-06-27 06:10 UTC, kennyjhcheng requested changes
Todo:
* Add middleware to private routes
* Check controllers have @access documentation

2023-06-29 22:05 UTC, closed without merging