initial implementation of workout schedule history
d-x-s/airon-fitness pull request #44
Opened 2023-07-09 21:04 UTC by jakji93

- History is done by separate entries
- get latest by sorting on _id and get the first entry
- update is done by updating on the latest entry

Notes:
Create a new entry when requesting a new schedule
Currently update is done by updating on the latest entry without creating a new entry (option 1)
option2: creating a new entry when update as well (keeping a history of all the updated schedules)

2023-07-12 05:26 UTC, kennyjhcheng commented on server/src/utils/prompts/workoutPrompts.js
> -  Allergies (make sure the schedule is free of these allergen risks): ${user.allergies}
is this supposed to be removed?

2023-07-12 05:26 UTC, kennyjhcheng commented on server/src/utils/prompts/workoutPrompts.js
> -  Diet Restrictions: ${user.dietRestrictions}
Also is this supposed to be removed?

2023-07-12 05:29 UTC, jakji93 commented on server/src/utils/prompts/workoutPrompts.js
> -  Allergies (make sure the schedule is free of these allergen risks): ${user.allergies}
I dont think is need it to generate a workout prompt. Davis can decide, but remove can save a few tokens

2023-07-12 05:30 UTC, jakji93 commented on server/src/utils/prompts/workoutPrompts.js
> -  Diet Restrictions: ${user.dietRestrictions}
same as above, meant to save some cost

2023-07-12 06:04 UTC, kennyjhcheng commented on server/src/utils/prompts/workoutPrompts.js
> -  Diet Restrictions: ${user.dietRestrictions}
I agree, thanks for clarifying

2023-07-12 06:04 UTC, kennyjhcheng commented on server/src/utils/prompts/workoutPrompts.js
> -  Allergies (make sure the schedule is free of these allergen risks): ${user.allergies}
agreed

2023-07-12 06:04 UTC, kennyjhcheng approved these changes

2023-07-12 21:17 UTC, d-x-s commented
When will the user request a new schedule VS just updating their schedule?
If the custom inputs are used only for updating schedules, then there might not be a use case for Option 1. 

I might just not be on the same page about the implementation, let's discuss in our meeting today.

2023-07-12 21:18 UTC, d-x-s requested changes

2023-07-12 21:18 UTC, d-x-s commented on server/src/routes/WorkoutSchedule.js
> + * @desc get lastest workout schedule for user (Get userID from JWT token)
lastest --> latest

2023-07-13 17:13 UTC, jakji93 commented on server/src/routes/WorkoutSchedule.js
> + * @desc get lastest workout schedule for user (Get userID from JWT token)
Yea, the team can discuss the implementation in our next meeting. I don't think this will block anything for the FE or other core functions.
The case for option 1 depends on whether when user update their profile (goals, preference, etc), do we generate a new schedule (clears previous custom inputs) or making an update on the existing schedule. Option 1 is having generate a complete new schedule in mind.
Which ever option we pick regarding how update profile works, is not going to have a large impact on the current code base

2023-07-13 23:38 UTC, d-x-s commented on server/src/routes/WorkoutSchedule.js
> + * @desc get lastest workout schedule for user (Get userID from JWT token)
Cool, I don't mind merging this in then

2023-07-13 23:39 UTC, d-x-s submitted a review, later dismissed

2023-07-14 06:54 UTC, d-x-s commented on server/src/routes/WorkoutSchedule.js
> + * @desc get lastest workout schedule for user (Get userID from JWT token)
@jakji93 would you mind fixing this typo and then also changing the UserProfile schema to have a `schedules` object instead of a `schedule` object? Should be good to resolve and merge after that-- can discuss between Option 1 and Option 2 in a later PR. TY

2023-07-14 08:35 UTC, kennyjhcheng submitted a review, later dismissed

2023-07-14 18:49 UTC, d-x-s approved these changes

2023-07-14 18:52 UTC, kennyjhcheng approved these changes

2023-07-14 18:54 UTC, merged